export const LOAD_PARTNERTENANTPACKAGE = 'LOAD_PARTNERTENANTPACKAGE';

export const ADD_PARTNERTENANTPACKAGE= 'ADD_PARTNERTENANTPACKAGE';
export const EDIT_PARTNERTENANTPACKAGE= 'EDIT_PARTNERTENANTPACKAGE';
export const UPDATE_PARTNERTENANTPACKAGE= 'UPDATE_PARTNERTENANTPACKAGE';
export const DELETE_PARTNERTENANTPACKAGE= 'DELETE_PARTNERTENANTPACKAGE';
export const IS_FETCHING_PARTNERTENANTPACKAGE= 'IS_FETCHING_PARTNERTENANTPACKAGE';
export const FETCH_PARTNERTENANTPACKAGE_FILTER = 'FETCH_PARTNERTENANTPACKAGE_FILTER';
export const FIND_PARTNERTENANTPACKAGE= 'FIND_PARTNERTENANTPACKAGE';
export const COUNT_DATA= 'COUNT_DATA';
export const GET_PARTNER_NEAR_HIRE= 'GET_PARTNER_NEAR_HIRE';