export const LOAD_PROCEDURE = 'LOAD_PROCEDURE';

export const ADD_PROCEDURE= 'ADD_PROCEDURE';
export const EDIT_PROCEDURE= 'EDIT_PROCEDURE';
export const UPDATE_PROCEDURE= 'UPDATE_PROCEDURE';
export const DELETE_PROCEDURE= 'DELETE_PROCEDURE';
export const IS_FETCHING_PROCEDURE= 'IS_FETCHING_PROCEDURE';
export const FETCH_PROCEDURE_FILTER = 'FETCH_PROCEDURE_FILTER';
export const FIND_PROCEDURE= 'FIND_PROCEDURE';
export const COUNT_DATA= 'COUNT_DATA';