export const LOAD_TYPECAR = 'LOAD_TYPECAR';

export const ADD_TYPECAR= 'ADD_TYPECAR';
export const EDIT_TYPECAR= 'EDIT_TYPECAR';
export const UPDATE_TYPECAR= 'UPDATE_TYPECAR';
export const DELETE_TYPECAR= 'DELETE_TYPECAR';
export const IS_FETCHING_TYPECAR= 'IS_FETCHING_TYPECAR';
export const FETCH_TYPECAR_FILTER = 'FETCH_TYPECAR_FILTER';
export const FIND_TYPECAR= 'FIND_TYPECAR';
export const COUNT_DATA= 'COUNT_DATA';