export const LOAD_LOCATION = 'LOAD_LOCATION';

export const ADD_LOCATION= 'ADD_LOCATION';
export const EDIT_LOCATION= 'EDIT_LOCATION';
export const UPDATE_LOCATION= 'UPDATE_LOCATION';
export const DELETE_LOCATION= 'DELETE_LOCATION';
export const IS_FETCHING_LOCATION= 'IS_FETCHING_LOCATION';
export const FETCH_LOCATION_FILTER = 'FETCH_LOCATION_FILTER';
export const FIND_LOCATION= 'FIND_LOCATION';
export const COUNT_DATA= 'COUNT_DATA';
export const ALL_LOCATION= 'ALL_LOCATION';