export const LOAD_PAYMENT = 'LOAD_PAYMENT';

export const ADD_PAYMENT= 'ADD_PAYMENT';
export const EDIT_PAYMENT= 'EDIT_PAYMENT';
export const UPDATE_PAYMENT= 'UPDATE_PAYMENT';
export const DELETE_PAYMENT= 'DELETE_PAYMENT';
export const IS_FETCHING_PAYMENT= 'IS_FETCHING_PAYMENT';
export const FETCH_PAYMENT_FILTER = 'FETCH_PAYMENT_FILTER';
export const FIND_PAYMENT= 'FIND_PAYMENT';
export const COUNT_DATA= 'COUNT_DATA';