export const LOAD_CUSTOMER = 'LOAD_CUSTOMER';

export const ADD_CUSTOMER= 'ADD_CUSTOMER';
export const EDIT_CUSTOMER= 'EDIT_CUSTOMER';
export const UPDATE_CUSTOMER= 'UPDATE_CUSTOMER';
export const DELETE_CUSTOMER= 'DELETE_CUSTOMER';
export const IS_FETCHING_CUSTOMER= 'IS_FETCHING_CUSTOMER';
export const FETCH_CUSTOMER_FILTER = 'FETCH_CUSTOMER_FILTER';
export const FIND_CUSTOMER= 'FIND_CUSTOMER';
export const COUNT_DATA= 'COUNT_DATA';