export const LOAD_FEATURE = 'LOAD_FEATURE';

export const ADD_FEATURE= 'ADD_FEATURE';
export const EDIT_FEATURE= 'EDIT_FEATURE';
export const UPDATE_FEATURE= 'UPDATE_FEATURE';
export const DELETE_FEATURE= 'DELETE_FEATURE';
export const IS_FETCHING_FEATURE= 'IS_FETCHING_FEATURE';
export const FETCH_FEATURE_FILTER = 'FETCH_FEATURE_FILTER';
export const FIND_FEATURE= 'FIND_FEATURE';
export const COUNT_DATA= 'COUNT_DATA';