export const LOAD_PACKAGE = 'LOAD_PACKAGE';

export const ADD_PACKAGE= 'ADD_PACKAGE';
export const EDIT_PACKAGE= 'EDIT_PACKAGE';
export const UPDATE_PACKAGE= 'UPDATE_PACKAGE';
export const DELETE_PACKAGE= 'DELETE_PACKAGE';
export const IS_FETCHING_PACKAGE= 'IS_FETCHING_PACKAGE';
export const FETCH_PACKAGE_FILTER = 'FETCH_PACKAGE_FILTER';
export const FIND_PACKAGE= 'FIND_PACKAGE';
export const COUNT_DATA= 'COUNT_DATA';