export const LOAD_CAR_PARTNER = 'LOAD_CAR_PARTNER';

export const ADD_CAR_PARTNER= 'ADD_CAR_PARTNER';
export const EDIT_CAR_PARTNER= 'EDIT_CAR_PARTNER';
export const UPDATE_CAR_PARTNER= 'UPDATE_CAR_PARTNER';
export const DELETE_CAR_PARTNER= 'DELETE_CAR_PARTNER';
export const IS_FETCHING_CAR_PARTNER= 'IS_FETCHING_CAR_PARTNER';
export const FETCH_CAR_PARTNER_FILTER = 'FETCH_CAR_PARTNER_FILTER';
export const FIND_CAR_PARTNER= 'FIND_CAR_PARTNER';
export const COUNT_DATA_CAR_PARTNER= 'COUNT_DATA_CAR_PARTNER';
export const LOAD_CAR_PARTNER_FILTER_LOCATION_AND_DATE= 'LOAD_CAR_PARTNER_FILTER_LOCATION_AND_DATE';