export const LOAD_PARTNER = 'LOAD_PARTNER';

export const ADD_PARTNER= 'ADD_PARTNER';
export const EDIT_PARTNER= 'EDIT_PARTNER';
export const UPDATE_PARTNER= 'UPDATE_PARTNER';
export const DELETE_PARTNER= 'DELETE_PARTNER';
export const IS_FETCHING_PARTNER= 'IS_FETCHING_PARTNER';
export const FETCH_PARTNER_FILTER = 'FETCH_PARTNER_FILTER';
export const FIND_PARTNER= 'FIND_PARTNER';
export const COUNT_DATA= 'COUNT_DATA';